name: Dockerfile validation

on:
  pull_request:
    branches: [ develop, master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
        cd ./ShareBook
        docker build . --file ./devops/Dockerfile --tag my-image-name:$(date +%s)
